### ISSUE TITLE
Pictures in GetHotelList are missing

### ISSUE THREAD

**Issue by PhilippSchoenauer** [bookingsuedtirol/mss-dotnet#2]
```c#
request.Request.Options = new Options
{
    HotelDetails = (int)(HotelDetails.HeaderImages | HotelDetails.Gallery),
;
```
returns for each setting an image with null fields instead of the full list of existing images.

![image](https://user-images.githubusercontent.com/56018578/66654996-9e071280-ec3b-11e9-965b-be3389deaba7.png)

**Comment by francesconi** [comment]
Fixed with 1424ec208c9084d9bd09aaa2bb031a5bc02d9684
